# Generated by Django 5.1.2 on 2024-10-10 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsss", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("employee", "Employee"),
                            ("staff", "Staff"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STCS", "School of Technology and Computer Science"),
                            ("SCJE", "School of Criminal Justice and Education"),
                            ("SAS", "School of Arts and Sciences"),
                            ("SME", "School of Management and Entrepreneurship"),
                            ("SOE", "School of Engineering"),
                            ("SNHS", "School of Nursing and Health Sciences"),
                            ("LHS", "Liberal Arts and Humanities"),
                            ("STED", "School of Teacher Education"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "student_id_image",
                    models.ImageField(blank=True, null=True, upload_to="student_ids/"),
                ),
                (
                    "study_load_image",
                    models.ImageField(blank=True, null=True, upload_to="study_loads/"),
                ),
                (
                    "employee_id_image",
                    models.ImageField(blank=True, null=True, upload_to="employee_ids/"),
                ),
                (
                    "document_image",
                    models.ImageField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
